name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [18, 20, 22, 24]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - run: pnpm install && pnpm test -- --bail 1
      - run: pnpm build && npm publish --dry-run

      - uses: codecov/codecov-action@v4
        if: matrix.os == 'ubuntu-latest' && matrix.node == 24
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Set up browser tests
        working-directory: tests-browser
        run: pnpm install && pnpm exec playwright install chromium firefox
        if: matrix.node != 18

      - name: Install webkit browser on macos
        working-directory: tests-browser
        run: pnpm exec playwright install
        if: matrix.node != 18 && matrix.os == 'macos-latest'

      - name: Run browser tests (chromium)
        run: pnpm test:browser --browser=chromium
        if: matrix.node != 18

      - name: Run browser tests (firefox)
        run: pnpm test:browser --browser=firefox
        if: matrix.node != 18

      - name: Run browser tests (webkit)
        run: |
          pnpm test:browser --browser=webkit
        if: matrix.node != 18 && matrix.os == 'macos-latest'

  check-runtimes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - run: pnpm install && pnpm build && cd example && pnpm install

      - name: check main.js
        run: |
          ./scripts/check-runtime.sh example/main.js

      - name: check main.js on mininum supported node version
        run: |
          curl -sL https://nodejs.org/download/release/v16.0.0/node-v16.0.0-linux-x64.tar.gz | tar -xz
          ./node-v16.0.0-linux-x64/bin/node example/main.js && rm -rf node-v16.0.0-linux-x64
